const $=id=>document.getElementById(id);
const DEMO_USERS=[
 {username:'admin',email:'admin@example.test',password:'AdminDemo123!',role:'admin',name:'System Admin',active:true,approval:'approved'},
 ...Array.from({length:10},(_,i)=>({username:`caller${String(i+1).padStart(2,'0')}`,email:`caller${String(i+1).padStart(2,'0')}@example.test`,password:'CallerDemo123!',role:'caller',name:`Caller ${String(i+1).padStart(2,'0')}`,active:true,approval:'approved'}))
];
const DB_KEY='re_caller_desk_v1';
const USERS_KEY='re_caller_users_v1';
let USERS=[];
let session=null, leads=[], activeTab='leads';
const LAN_MODE=location.protocol.startsWith('http:') && !location.hostname.endsWith('github.io');
let apiToken=sessionStorage.getItem('re_caller_api_token')||'';
async function api(path, options={}) {
  const headers={'content-type':'application/json',...(options.headers||{})};
  if(apiToken) headers.authorization='Bearer '+apiToken;
  const response=await fetch('/api'+path,{...options,headers});
  const data=await response.json().catch(()=>({error:'Invalid server response'}));
  if(!response.ok) throw new Error(data.error||'Server request failed');
  return data;
}
async function syncServerData(){
  if(!LAN_MODE||!apiToken)return;
  const data=await api('/leads');leads=data.leads||[];
  if(isAdmin()){const users=await api('/admin/users');USERS=users.users||[];}
}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
function readData(){if(LAN_MODE){leads=[];return}try{leads=JSON.parse(localStorage.getItem(DB_KEY)||'[]')}catch{leads=[]}}
function readUsers(){try{const saved=JSON.parse(localStorage.getItem(USERS_KEY)||'null');USERS=Array.isArray(saved)&&saved.length?saved:DEMO_USERS.map(u=>({...u,id:uid()}));if(!USERS.some(u=>u.role==='admin'&&u.active))USERS=DEMO_USERS.map(u=>({...u,id:uid()}));USERS=USERS.map(u=>({...u,approval:u.approval||'approved'}));writeUsers()}catch{USERS=DEMO_USERS.map(u=>({...u,id:uid()}));writeUsers()}}
function writeUsers(){localStorage.setItem(USERS_KEY,JSON.stringify(USERS))}
function writeData(){if(!LAN_MODE)localStorage.setItem(DB_KEY,JSON.stringify(leads))}
function isAdmin(){return session?.role==='admin'}
function myLeads(){return isAdmin()?leads:leads.filter(x=>x.assignedTo===(LAN_MODE?session.id:session.username))}
function setConnection(){const el=$('connection');el.textContent=navigator.onLine?'Online':'Offline mode';el.style.background=navigator.onLine?'#d8f3e3':'#fff0c2';el.style.color=navigator.onLine?'#17633b':'#785400'}
window.addEventListener('online',setConnection);window.addEventListener('offline',setConnection);setConnection();
function showLogin(){if(LAN_MODE&&apiToken){api('/auth/logout',{method:'POST'}).catch(()=>{});apiToken='';sessionStorage.removeItem('re_caller_api_token')}session=null;$('appView').hidden=true;$('loginView').hidden=false;$('password').value='';}
async function login(){const otpMode=$('loginMethod').value==='otp',u=(otpMode?($('otpDestination').value.trim()||$('username').value.trim()):$('username').value.trim()).toLowerCase(),p=$('password').value;try{let user;if(LAN_MODE){const method=$('loginMethod').value;const result=method==='otp'?await api('/auth/verify-otp',{method:'POST',body:JSON.stringify({username:u,code:$('otpCode').value.trim()})}):await api('/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})});apiToken=result.token;sessionStorage.setItem('re_caller_api_token',apiToken);user=result.user;}else{user=USERS.find(x=>(x.username.toLowerCase()===u||(x.email||'').toLowerCase()===u)&&x.password===p&&x.active);if(!user)throw new Error('Login failed. Check username/password or account status.');if(user.approval!=='approved')throw new Error(user.approval==='rejected'?'Admin has rejected this account.':'Your account is pending Admin approval.');}session={id:user.id,username:user.username,name:user.name,role:user.role};await syncServerData();$('loginError').textContent='';$('loginView').hidden=true;$('appView').hidden=false;$('who').textContent=user.name;$('roleText').textContent=user.role==='admin'?'Administrator · Shared LAN database':'Caller · Only server-authorized assigned leads';$('securityNotice').textContent=LAN_MODE?'LAN server mode: login, approval and lead ownership are checked by the Windows server. Keep this app on your trusted private network.':'Prototype warning: browser-only login and data are not secure. Do not enter real customer data on the public demo.';document.querySelectorAll('.admin-only').forEach(x=>x.hidden=!isAdmin());render();switchTab('leads')}catch(err){$('loginError').textContent=err.message||'Login failed.'}}
function switchTab(tab){activeTab=tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.tabbody').forEach(x=>x.hidden=true);$(`${tab}Tab`).hidden=false;if(tab==='followups')renderFollowups();if(tab==='visits')renderVisits();if(tab==='users')renderUsers();if(tab==='leads')renderLeads()}
function render(){renderLeads();renderFollowups();renderVisits();renderUsers()}
function renderLeads(){const q=$('search').value.toLowerCase(),f=$('statusFilter').value;const arr=myLeads().filter(x=>(!f||x.status===f)&&(!q||[x.name,x.mobile,x.area,x.notes].some(v=>String(v||'').toLowerCase().includes(q))));$('stats').innerHTML=[['My visible leads',arr.length],['Hot leads',arr.filter(x=>x.status==='Hot').length],['Visits confirmed',arr.filter(x=>x.visitStatus==='Confirmed').length],['Follow-ups due',arr.filter(x=>x.followDate&&x.followDate<=new Date().toISOString().slice(0,10)).length]].map(([a,b])=>`<div class="stat"><b>${b}</b><span>${a}</span></div>`).join('');$('leadRows').innerHTML=arr.map(x=>`<tr><td><b>${esc(x.name)}</b><span class="subline">${esc(x.area||'Area not set')}</span></td><td>${esc(x.mobile)}${x.whatsapp?`<span class="subline">WA: ${esc(x.whatsapp)}</span>`:''}</td><td>${esc([x.budget,x.bhk,x.propertyType].filter(Boolean).join(' · ')||'Not specified')}</td><td><span class="tag ${x.status.toLowerCase().replaceAll(' ','-')}">${esc(x.status)}</span></td><td>${esc(x.followDate||'—')} ${esc(x.followTime||'')}</td><td><button class="rowbtn" data-edit="${esc(x.id)}">Edit</button></td></tr>`).join('');$('emptyLeads').hidden=arr.length!==0;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openLead(b.dataset.edit))}
function openLead(id){const x=id?leads.find(y=>y.id===id):null;if(x&&!isAdmin()&&x.assignedTo!==(LAN_MODE?session.id:session.username))return; $('leadForm').reset();$('leadId').value=x?.id||'';$('dialogTitle').textContent=x?'Edit lead':'Add lead';$('deleteLeadBtn').hidden=!x;$('assignToWrap').hidden=!isAdmin();if(isAdmin()){$('assignTo').innerHTML=USERS.filter(u=>u.role==='caller'&&u.active&&u.approval==='approved').map(u=>`<option value="${esc(u.id)}">${esc(u.name)} (${esc(u.username)})</option>`).join('');if(x?.assignedTo)$('assignTo').value=x.assignedTo;}const fields=['name','mobile','whatsapp','email','area','budget','bhk','propertyType','status','callOutcome','followDate','followTime','visitDate','visitTime','visitStatus','notes'];const map={name:'customerName',mobile:'mobile',whatsapp:'whatsapp',email:'email',area:'area',budget:'budget',bhk:'bhk',propertyType:'propertyType',status:'status',callOutcome:'callOutcome',followDate:'followDate',followTime:'followTime',visitDate:'visitDate',visitTime:'visitTime',visitStatus:'visitStatus',notes:'notes'};fields.forEach(k=>$(map[k]).value=x?.[k]|| (k==='status'?'New':''));$('leadDialog').showModal()}
async function saveLead(e){e.preventDefault();const id=$('leadId').value;let old=id?leads.find(x=>x.id===id):null;if(old&&!isAdmin()&&old.assignedTo!==(LAN_MODE?session.id:session.username))return;const val={id:id||uid(),assignedTo:old?.assignedTo||(isAdmin()?$('assignTo')?.value||'caller01':session.username),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const map={name:'customerName',mobile:'mobile',whatsapp:'whatsapp',email:'email',area:'area',budget:'budget',bhk:'bhk',propertyType:'propertyType',status:'status',callOutcome:'callOutcome',followDate:'followDate',followTime:'followTime',visitDate:'visitDate',visitTime:'visitTime',visitStatus:'visitStatus',notes:'notes'};Object.entries(map).forEach(([k,v])=>val[k]=$(v).value.trim());if(LAN_MODE){try{const payload={...val};delete payload.id;delete payload.createdAt;delete payload.updatedAt;if(!isAdmin())delete payload.assignedTo;else payload.assignedTo=$('assignTo').value;if(old){await api('/leads/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(payload)})}else{const result=await api('/leads',{method:'POST',body:JSON.stringify(payload)});val.id=result.lead.id;val.assignedTo=result.lead.assignedTo;val.createdAt=result.lead.createdAt;val.updatedAt=result.lead.updatedAt}await syncServerData()}catch(err){alert('Could not save lead: '+err.message);return}}else{if(old)leads=leads.map(x=>x.id===id?{...old,...val}:x);else leads.unshift(val);writeData()}$('leadDialog').close();render()}
function renderFollowups(){const arr=myLeads().filter(x=>x.followDate).sort((a,b)=>a.followDate.localeCompare(b.followDate));$('followupList').innerHTML=arr.length?arr.map(x=>card(x,`${x.followDate} ${x.followTime||''}`,x.notes||'No note')).join(''):'<p class="empty">No follow-ups scheduled.</p>';wireCards()}
function renderVisits(){const arr=myLeads().filter(x=>x.visitDate).sort((a,b)=>a.visitDate.localeCompare(b.visitDate));$('visitList').innerHTML=arr.length?arr.map(x=>card(x,`${x.visitDate} ${x.visitTime||''}`,`Visit status: ${x.visitStatus||'Proposed'}`)).join(''):'<p class="empty">No site visits scheduled.</p>';wireCards()}
function card(x,when,desc){return `<article class="itemcard"><div><h3>${esc(x.name)} <span class="tag">${esc(x.status)}</span></h3><p>${esc(x.mobile)} · ${esc(x.area||'Area not set')}</p><p><b>${esc(when)}</b> · ${esc(desc)}</p></div><button class="rowbtn" data-edit="${esc(x.id)}">Open</button></article>`}
function wireCards(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openLead(b.dataset.edit))}
function renderUsers(){if(!isAdmin())return;$('userList').innerHTML=USERS.map(x=>'<article class="itemcard"><div><h3>'+esc(x.name)+'</h3><p>Username: '+esc(x.username)+' · '+esc(x.email||'No email')+'</p><p>Role: '+esc(x.role)+' · '+(x.active?'Active':'Disabled')+' · Approval: '+esc(x.approval||'pending')+'</p></div><div class="useractions"><button type="button" class="rowbtn" data-user-edit="'+esc(x.id)+'">Edit / password</button><button type="button" class="rowbtn" data-user-approval="'+esc(x.id)+'" data-approval="'+((x.approval||'pending')==='approved'?'rejected':'approved')+'">'+((x.approval||'pending')==='approved'?'Revoke approval':'Approve caller')+'</button><button type="button" class="rowbtn" data-user-toggle="'+esc(x.id)+'">'+(x.active?'Disable':'Enable')+'</button></div></article>').join('');document.querySelectorAll('[data-user-edit]').forEach(b=>b.onclick=()=>editUser(b.dataset.userEdit));document.querySelectorAll('[data-user-toggle]').forEach(b=>b.onclick=()=>toggleUser(b.dataset.userToggle));document.querySelectorAll('[data-user-approval]').forEach(b=>b.onclick=()=>setUserApproval(b.dataset.userApproval,b.dataset.approval))}
function editUser(id){if(!isAdmin())return;const u=USERS.find(x=>x.id===id);if(!u)return;$('editUserId').value=u.id;$('userName').value=u.name;$('userUsername').value=u.username;$('userEmail').value=u.email||'';$('userPassword').value='';$('userRole').value=u.role;$('userApproval').value=u.approval||'pending';$('userActive').checked=!!u.active;$('userSaveBtn').textContent='Update user';$('userMessage').textContent='Editing '+u.username+'. Leave password blank to keep it unchanged.'}
function clearUserForm(){$('userForm').reset();$('editUserId').value='';$('userActive').checked=true;$('userRole').value='caller';$('userApproval').value='pending';$('userSaveBtn').textContent='Create user'}
async function saveUser(e){e.preventDefault();if(!isAdmin())return;const id=$('editUserId').value,name=$('userName').value.trim(),username=$('userUsername').value.trim().toLowerCase(),email=$('userEmail').value.trim().toLowerCase(),password=$('userPassword').value,role=$('userRole').value,approval=$('userApproval').value,active=$('userActive').checked,old=USERS.find(x=>x.id===id);if(USERS.some(x=>x.id!==id&&(x.username.toLowerCase()===username||(email&&String(x.email||'').toLowerCase()===email)))){$('userMessage').textContent='Username or email already exists.';return}if(!old&&!password){$('userMessage').textContent='Enter a password for the new account.';return}if(password&&password.length<(LAN_MODE?10:8)){$('userMessage').textContent='Password must be at least '+(LAN_MODE?10:8)+' characters.';return}if(LAN_MODE){try{let result;if(old){const payload={name,username,email,role};if(password)payload.password=password;result=await api('/admin/users/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(payload)});if((old.approval||'pending')!==approval)await api('/admin/users/'+encodeURIComponent(id)+'/approval',{method:'PATCH',body:JSON.stringify({approval})});if(!!old.active!==active)await api('/admin/users/'+encodeURIComponent(id)+'/active',{method:'PATCH',body:JSON.stringify({active})})}else{await api('/admin/users',{method:'POST',body:JSON.stringify({name,username,email,password,role,approval,active})})}await syncServerData();clearUserForm();$('userMessage').textContent='User saved on the Windows LAN server.';renderUsers();renderLeads();return}catch(err){$('userMessage').textContent=err.message;return}}if(USERS.some(x=>x.id!==id&&(x.username.toLowerCase()===username||(email&&String(x.email||'').toLowerCase()===email)))){$('userMessage').textContent='Username or email already exists.';return}if(old&&old.role==='admin'&&old.active&&(!active||role!=='admin')&&USERS.filter(x=>x.active&&x.role==='admin').length===1){$('userMessage').textContent='The last active Admin cannot be disabled or demoted.';return}const next={id:id||uid(),name,username,email,role,active,approval:old?approval:(role==='admin'?'approved':approval),password:password||(old&&old.password)||''};if(old){USERS=USERS.map(x=>x.id===id?next:x);if(old.username!==username)leads=leads.map(l=>l.assignedTo===old.username?{...l,assignedTo:username,updatedAt:new Date().toISOString()}:l);if(session&&session.username===old.username){session={...session,username:username,name:name,role:role};if(!active){writeUsers();writeData();showLogin();$('loginError').textContent='This account is disabled.';return}}}else USERS.push(next);writeUsers();writeData();clearUserForm();$('userMessage').textContent='User saved in this browser.';renderUsers();renderLeads()}
async function setUserApproval(id,approval){if(!isAdmin())return;if(LAN_MODE){try{await api('/admin/users/'+encodeURIComponent(id)+'/approval',{method:'PATCH',body:JSON.stringify({approval})});await syncServerData();$('userMessage').textContent='Approval updated on the LAN server.';renderUsers()}catch(err){$('userMessage').textContent=err.message}return}const u=USERS.find(x=>x.id===id);if(!u)return;u.approval=approval;writeUsers();$('userMessage').textContent=u.name+': '+(approval==='approved'?'approved':'approval revoked')+'.';renderUsers()}
async function toggleUser(id){if(!isAdmin())return;if(LAN_MODE){const u=USERS.find(x=>x.id===id);if(!u)return;try{await api('/admin/users/'+encodeURIComponent(id)+'/active',{method:'PATCH',body:JSON.stringify({active:!u.active})});await syncServerData();$('userMessage').textContent='Account status updated on the LAN server.';renderUsers()}catch(err){$('userMessage').textContent=err.message}return}const u=USERS.find(x=>x.id===id);if(!u)return;if(u.role==='admin'&&u.active&&USERS.filter(x=>x.active&&x.role==='admin').length===1){$('userMessage').textContent='The last active Admin cannot be disabled.';return}u.active=!u.active;writeUsers();if(session&&session.username===u.username&&!u.active){showLogin();$('loginError').textContent='This account is disabled.'}renderUsers()}
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
$('userForm').onsubmit=saveUser;$('userCancelBtn').onclick=()=>{clearUserForm();$('userMessage').textContent=''};
$('loginBtn').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('loginMethod').onchange=()=>{const otp=$('loginMethod').value==='otp';$('passwordLoginFields').hidden=otp;$('otpLoginFields').hidden=!otp;$('loginError').textContent=''};$('requestOtpBtn').onclick=async()=>{if(!LAN_MODE){$('loginError').textContent='OTP requires the Windows LAN server.';return}try{const r=await api('/auth/request-otp',{method:'POST',body:JSON.stringify({username:$('otpDestination').value.trim().toLowerCase()||$('username').value.trim().toLowerCase()})});$('loginError').textContent=r.message||'Check the Windows server console for the OTP.'}catch(err){$('loginError').textContent=err.message}};$('verifyOtpBtn').onclick=()=>login();$('logoutBtn').onclick=showLogin;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('newLeadBtn').onclick=()=>openLead();$('closeDialog').onclick=()=>$('leadDialog').close();$('cancelLeadBtn').onclick=()=>$('leadDialog').close();$('leadForm').onsubmit=saveLead;$('search').oninput=renderLeads;$('statusFilter').onchange=renderLeads;
$('deleteLeadBtn').onclick=async()=>{const id=$('leadId').value,x=leads.find(y=>y.id===id);if(!x)return;if(!isAdmin()&&x.assignedTo!==(LAN_MODE?session.id:session.username))return;if(confirm('Delete this lead?')){try{if(LAN_MODE){await api('/leads/'+encodeURIComponent(id),{method:'DELETE'});await syncServerData()}else{leads=leads.filter(y=>y.id!==id);writeData()}$('leadDialog').close();render()}catch(err){alert('Delete failed: '+err.message)}}};
$('exportJson').onclick=async()=>{if(!isAdmin())return;try{let backup;if(LAN_MODE){backup=await api('/admin/backup')}else{backup={version:1,exportedAt:new Date().toISOString(),leads,warning:'Prototype local data; protect this backup.'}}download('caller-desk-backup.json',JSON.stringify(backup,null,2),'application/json');$('backupMessage').textContent='Backup downloaded. Keep it in a protected location.'}catch(err){$('backupMessage').textContent='Backup failed: '+err.message}};
$('exportCsv').onclick=()=>{const arr=myLeads(),keys=['name','mobile','whatsapp','email','area','budget','bhk','propertyType','status','callOutcome','followDate','followTime','visitDate','visitTime','visitStatus','notes','assignedTo'];const out=[keys.join(','),...arr.map(x=>keys.map(k=>csv(x[k])).join(','))].join('\r\n');download('caller-leads.csv','\ufeff'+out,'text/csv;charset=utf-8');$('backupMessage').textContent='CSV exported.'};
$('importJson').onchange=async e=>{if(!isAdmin())return;const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(LAN_MODE?!(data.version===1&&data.database&&Array.isArray(data.database.leads)):!Array.isArray(data.leads))throw Error('Invalid backup format for this mode');if(LAN_MODE){if(!confirm('Restore this backup to the shared LAN server? The server will save a pre-restore backup and all users will need to sign in again.'))return;const result=await api('/admin/restore',{method:'POST',body:JSON.stringify(data)});$('backupMessage').textContent=result.message||'Server backup restored.';showLogin();$('loginError').textContent='Backup restored. Please sign in again.'}else if(confirm(`Restore ${data.leads.length} records? This replaces local records.`)){leads=data.leads;writeData();render();$('backupMessage').textContent='Backup restored.'}}catch(err){$('backupMessage').textContent='Restore failed: '+err.message}e.target.value=''};
readData();
readUsers();
if(LAN_MODE){setInterval(async()=>{if(!apiToken||!session)return;try{await syncServerData();if(!$('leadDialog').open)render()}catch(err){if(/sign in again/i.test(err.message)){showLogin();$('loginError').textContent='Session expired. Please sign in again.'}}},15000)}
if('serviceWorker'in navigator && location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
