const $=id=>document.getElementById(id);
const DEMO_USERS=[
 {username:'admin',email:'admin@example.test',password:'AdminDemo123!',role:'admin',name:'System Admin',active:true},
 ...Array.from({length:10},(_,i)=>({username:`caller${String(i+1).padStart(2,'0')}`,email:`caller${String(i+1).padStart(2,'0')}@example.test`,password:'CallerDemo123!',role:'caller',name:`Caller ${String(i+1).padStart(2,'0')}`,active:true}))
];
const DB_KEY='re_caller_desk_v1';
let session=null, leads=[], activeTab='leads';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
function readData(){try{leads=JSON.parse(localStorage.getItem(DB_KEY)||'[]')}catch{leads=[]}}
function writeData(){localStorage.setItem(DB_KEY,JSON.stringify(leads))}
function isAdmin(){return session?.role==='admin'}
function myLeads(){return isAdmin()?leads:leads.filter(x=>x.assignedTo===session.username)}
function setConnection(){const el=$('connection');el.textContent=navigator.onLine?'Online':'Offline mode';el.style.background=navigator.onLine?'#d8f3e3':'#fff0c2';el.style.color=navigator.onLine?'#17633b':'#785400'}
window.addEventListener('online',setConnection);window.addEventListener('offline',setConnection);setConnection();
function showLogin(){session=null;$('appView').hidden=true;$('loginView').hidden=false;$('password').value='';}
function login(){const u=$('username').value.trim().toLowerCase(),p=$('password').value;const user=DEMO_USERS.find(x=>(x.username===u||x.email===u)&&x.password===p&&x.active);if(!user){$('loginError').textContent='Login failed. Check demo username/password.';return}session={username:user.username,name:user.name,role:user.role};$('loginError').textContent='';$('loginView').hidden=true;$('appView').hidden=false;$('who').textContent=user.name;$('roleText').textContent=user.role==='admin'?'Administrator · All local demo records':'Caller · Only records assigned to this demo account';$('securityNotice').textContent='Prototype warning: access filtering and demo passwords are implemented in browser code only. This is not secure isolation. Do not enter real customer data until a backend with server-side authentication and database RLS is connected.';document.querySelectorAll('.admin-only').forEach(x=>x.hidden=!isAdmin());render();switchTab('leads')}
function switchTab(tab){activeTab=tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.tabbody').forEach(x=>x.hidden=true);$(`${tab}Tab`).hidden=false;if(tab==='followups')renderFollowups();if(tab==='visits')renderVisits();if(tab==='users')renderUsers();if(tab==='leads')renderLeads()}
function render(){renderLeads();renderFollowups();renderVisits();renderUsers()}
function renderLeads(){const q=$('search').value.toLowerCase(),f=$('statusFilter').value;const arr=myLeads().filter(x=>(!f||x.status===f)&&(!q||[x.name,x.mobile,x.area,x.notes].some(v=>String(v||'').toLowerCase().includes(q))));$('stats').innerHTML=[['My visible leads',arr.length],['Hot leads',arr.filter(x=>x.status==='Hot').length],['Visits confirmed',arr.filter(x=>x.visitStatus==='Confirmed').length],['Follow-ups due',arr.filter(x=>x.followDate&&x.followDate<=new Date().toISOString().slice(0,10)).length]].map(([a,b])=>`<div class="stat"><b>${b}</b><span>${a}</span></div>`).join('');$('leadRows').innerHTML=arr.map(x=>`<tr><td><b>${esc(x.name)}</b><span class="subline">${esc(x.area||'Area not set')}</span></td><td>${esc(x.mobile)}${x.whatsapp?`<span class="subline">WA: ${esc(x.whatsapp)}</span>`:''}</td><td>${esc([x.budget,x.bhk,x.propertyType].filter(Boolean).join(' · ')||'Not specified')}</td><td><span class="tag ${x.status.toLowerCase().replaceAll(' ','-')}">${esc(x.status)}</span></td><td>${esc(x.followDate||'—')} ${esc(x.followTime||'')}</td><td><button class="rowbtn" data-edit="${esc(x.id)}">Edit</button></td></tr>`).join('');$('emptyLeads').hidden=arr.length!==0;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openLead(b.dataset.edit))}
function openLead(id){const x=id?leads.find(y=>y.id===id):null;if(x&&!isAdmin()&&x.assignedTo!==session.username)return; $('leadForm').reset();$('leadId').value=x?.id||'';$('dialogTitle').textContent=x?'Edit lead':'Add lead';$('deleteLeadBtn').hidden=!x;const fields=['name','mobile','whatsapp','email','area','budget','bhk','propertyType','status','callOutcome','followDate','followTime','visitDate','visitTime','visitStatus','notes'];const map={name:'customerName',mobile:'mobile',whatsapp:'whatsapp',email:'email',area:'area',budget:'budget',bhk:'bhk',propertyType:'propertyType',status:'status',callOutcome:'callOutcome',followDate:'followDate',followTime:'followTime',visitDate:'visitDate',visitTime:'visitTime',visitStatus:'visitStatus',notes:'notes'};fields.forEach(k=>$(map[k]).value=x?.[k]|| (k==='status'?'New':''));$('leadDialog').showModal()}
function saveLead(e){e.preventDefault();const id=$('leadId').value;let old=id?leads.find(x=>x.id===id):null;if(old&&!isAdmin()&&old.assignedTo!==session.username)return;const val={id:id||uid(),assignedTo:old?.assignedTo||(isAdmin()?$('assignTo')?.value||'caller01':session.username),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const map={name:'customerName',mobile:'mobile',whatsapp:'whatsapp',email:'email',area:'area',budget:'budget',bhk:'bhk',propertyType:'propertyType',status:'status',callOutcome:'callOutcome',followDate:'followDate',followTime:'followTime',visitDate:'visitDate',visitTime:'visitTime',visitStatus:'visitStatus',notes:'notes'};Object.entries(map).forEach(([k,v])=>val[k]=$(v).value.trim());if(old)leads=leads.map(x=>x.id===id?{...old,...val}:x);else leads.unshift(val);writeData();$('leadDialog').close();render()}
function renderFollowups(){const arr=myLeads().filter(x=>x.followDate).sort((a,b)=>a.followDate.localeCompare(b.followDate));$('followupList').innerHTML=arr.length?arr.map(x=>card(x,`${x.followDate} ${x.followTime||''}`,x.notes||'No note')).join(''):'<p class="empty">No follow-ups scheduled.</p>';wireCards()}
function renderVisits(){const arr=myLeads().filter(x=>x.visitDate).sort((a,b)=>a.visitDate.localeCompare(b.visitDate));$('visitList').innerHTML=arr.length?arr.map(x=>card(x,`${x.visitDate} ${x.visitTime||''}`,`Visit status: ${x.visitStatus||'Proposed'}`)).join(''):'<p class="empty">No site visits scheduled.</p>';wireCards()}
function card(x,when,desc){return `<article class="itemcard"><div><h3>${esc(x.name)} <span class="tag">${esc(x.status)}</span></h3><p>${esc(x.mobile)} · ${esc(x.area||'Area not set')}</p><p><b>${esc(when)}</b> · ${esc(desc)}</p></div><button class="rowbtn" data-edit="${esc(x.id)}">Open</button></article>`}
function wireCards(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openLead(b.dataset.edit))}
function renderUsers(){if(!isAdmin())return;$('userList').innerHTML=DEMO_USERS.map(x=>`<article class="itemcard"><div><h3>${esc(x.name)}</h3><p>${esc(x.username)} · ${esc(x.email)}</p><p>Role: ${esc(x.role)} · ${x.active?'Active':'Disabled'}</p></div><span class="tag">${x.role==='admin'?'Admin':'Caller'}</span></article>`).join('')}
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csv(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
$('loginBtn').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutBtn').onclick=showLogin;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('newLeadBtn').onclick=()=>openLead();$('closeDialog').onclick=()=>$('leadDialog').close();$('cancelLeadBtn').onclick=()=>$('leadDialog').close();$('leadForm').onsubmit=saveLead;$('search').oninput=renderLeads;$('statusFilter').onchange=renderLeads;
$('deleteLeadBtn').onclick=()=>{const id=$('leadId').value,x=leads.find(y=>y.id===id);if(!x)return;if(!isAdmin()&&x.assignedTo!==session.username)return;if(confirm('Delete this lead from this device?')){leads=leads.filter(y=>y.id!==id);writeData();$('leadDialog').close();render()}};
$('exportJson').onclick=()=>{if(!isAdmin())return;download('caller-desk-backup.json',JSON.stringify({version:1,exportedAt:new Date().toISOString(),leads,warning:'Prototype local data; protect this backup.'},null,2),'application/json');$('backupMessage').textContent='Backup downloaded.'};
$('exportCsv').onclick=()=>{const arr=myLeads(),keys=['name','mobile','whatsapp','email','area','budget','bhk','propertyType','status','callOutcome','followDate','followTime','visitDate','visitTime','visitStatus','notes','assignedTo'];const out=[keys.join(','),...arr.map(x=>keys.map(k=>csv(x[k])).join(','))].join('\r\n');download('caller-leads.csv','\ufeff'+out,'text/csv;charset=utf-8');$('backupMessage').textContent='CSV exported.'};
$('importJson').onchange=async e=>{if(!isAdmin())return;const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.leads))throw Error('Invalid backup format');if(confirm(`Restore ${data.leads.length} records? This replaces local records.`)){leads=data.leads;writeData();render();$('backupMessage').textContent='Backup restored.'}}catch(err){$('backupMessage').textContent='Restore failed: '+err.message}e.target.value=''};
readData();
if('serviceWorker'in navigator && location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
